# Rustfmt configuration for Homo-Habits
# Ensures consistent code formatting across the entire project

# Edition to use for formatting
edition = "2021"

# Use verbose diff output
verbose = false

# Use formatted output from stdin
format_code_in_doc_comments = true

# Maximum width of comments and strings
comment_width = 100
max_width = 120

# Hard tabs or spaces
hard_tabs = false
tab_spaces = 4

# Where to put the opening brace
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# How to indent
indent_style = "Block"

# Where to put return type in function signature
fn_single_line = false
force_explicit_abi = true

# Import formatting
imports_indent = "Block"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# Use field init shorthand if possible
use_field_init_shorthand = true

# Use small heuristics
use_small_heuristics = "Default"

# Formatting of literal expressions
format_strings = true
format_macro_matchers = true
format_macro_bodies = true

# Array formatting
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50

# Function call formatting
fn_call_width = 60
fn_params_layout = "Tall"
fn_args_layout = "Tall"

# Struct formatting
struct_field_align_threshold = 0
struct_lit_single_line = true
struct_lit_width = 18
struct_variant_width = 35

# Enum formatting
enum_discrim_align_threshold = 0

# Match formatting
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false

# Control flow formatting
force_multiline_blocks = false
overflow_delimited_expr = false

# Operator formatting
spaces_around_ranges = false
binop_separator = "Front"

# Comment formatting
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Attribute formatting
attributes_on_same_line_as_field = true
attributes_on_same_line_as_variant = true

# Miscellaneous
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true

# Trailing comma
trailing_comma = "Vertical"
trailing_semicolon = true

# Line ending
newline_style = "Unix"

# Empty items
empty_item_single_line = true
struct_lit_single_line = true

# Spacing
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false

# Type formatting
type_punctuation_density = "Wide"

# Where clause formatting
where_single_line = false

# Formatting of specific items
format_generated_files = true

# Error handling
error_on_line_overflow = false
error_on_unformatted = false

# Report formatting issues
report_todo = "Always"
report_fixme = "Always"

# Skip formatting for specific items
skip_children = false

# Version sorting for imports
reorder_imports = true

# Merge imports from the same crate
merge_imports = false

# Force explicit abi
force_explicit_abi = true

# Color output
color = "Auto"

# Check mode (don't modify files, just check)
check = false

# Edition guide behavior
edition_guide = true

# Configuration file discovery
unstable_features = false

# Hexadecimal literal formatting
hex_literal_case = "Preserve"

# Required version (minimum rustfmt version required)
required_version = "1.6.0" 